# Generated by Django 4.1.4 on 2022-12-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('serialno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=225)),
                ('Phonenumber', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=100)),
                ('Content', models.TextField()),
            ],
        ),
    ]
